<?php

namespace Database\Seeders;

use App\Models\Driver;
use App\Models\Order;
use App\Models\Store;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $storesByCode = Store::pluck('id', 'code');
        // Driver codes now live on the linked user account.
        $driversByCode = Driver::with('user')->get()
            ->filter(fn (Driver $d) => $d->user?->code)
            ->mapWithKeys(fn (Driver $d) => [$d->user->code => $d->id]);

        $orders = [
            // Operational / board orders
            [
                'code' => 'ORD-8823-XYZ',
                'store' => 'downtown',
                'driver' => null,
                'customer' => 'Sarah Jenkins',
                'phone' => '+1 555-0142',
                'area' => 'North Zone',
                'address' => '214 Maple St, North District',
                'slot' => '10:00–12:00',
                'slot_label' => 'Today',
                'placed_at' => '08:14 AM',
                'urgent' => true,
                'value' => 84.50,
                'items' => 6,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'waiting',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8819-ABC',
                'store' => 'uptown',
                'driver' => 'DRV-4412',
                'customer' => 'Michael Chen',
                'phone' => '+1 555-0198',
                'area' => 'Central Zone',
                'address' => '88 Market Ave, Central',
                'slot' => '10:00–12:00',
                'slot_label' => 'Today',
                'placed_at' => '07:52 AM',
                'urgent' => false,
                'value' => 62.00,
                'items' => 4,
                'payment' => 'cod',
                'prep' => 'packing',
                'prep_pct' => 55,
                'delivery' => 'assigned',
                'eta' => '22m',
            ],
            [
                'code' => 'ORD-8815-QWE',
                'store' => 'westside',
                'driver' => null,
                'customer' => 'Emily Watson',
                'phone' => '+1 555-0110',
                'area' => 'West Zone',
                'address' => '15 Harbor Rd, Westside',
                'slot' => '12:00–14:00',
                'slot_label' => 'Today',
                'placed_at' => '07:41 AM',
                'urgent' => false,
                'value' => 145.50,
                'items' => 11,
                'payment' => 'apple',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'waiting',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8808-RST',
                'store' => 'harbor',
                'driver' => null,
                'customer' => 'James Parker',
                'phone' => '+1 555-0166',
                'area' => 'South Zone',
                'address' => '402 Oak Lane, South',
                'slot' => '10:00–12:00',
                'slot_label' => 'Today',
                'placed_at' => '07:18 AM',
                'urgent' => true,
                'value' => 39.90,
                'items' => 3,
                'payment' => 'online',
                'prep' => 'not_started',
                'prep_pct' => 0,
                'delivery' => 'new',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8801-LMN',
                'store' => 'downtown',
                'driver' => 'DRV-2281',
                'customer' => 'Priya Sharma',
                'phone' => '+1 555-0177',
                'area' => 'East Zone',
                'address' => '9 River Walk, East End',
                'slot' => '08:00–10:00',
                'slot_label' => 'Today',
                'placed_at' => '06:55 AM',
                'urgent' => false,
                'value' => 98.25,
                'items' => 8,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'out',
                'eta' => '14m',
            ],
            [
                'code' => 'ORD-8794-TUV',
                'store' => 'uptown',
                'driver' => 'DRV-3390',
                'customer' => 'Robert Davis',
                'phone' => '+1 555-0133',
                'area' => 'North Zone',
                'address' => '71 Pine Court, North',
                'slot' => '14:00–16:00',
                'slot_label' => 'Today',
                'placed_at' => '06:40 AM',
                'urgent' => false,
                'value' => 54.00,
                'items' => 5,
                'payment' => 'cod',
                'prep' => 'packing',
                'prep_pct' => 40,
                'delivery' => 'accepted',
                'eta' => '35m',
            ],
            [
                'code' => 'ORD-8788-OPQ',
                'store' => 'downtown',
                'driver' => null,
                'customer' => 'Lisa Nguyen',
                'phone' => '+1 555-0188',
                'area' => 'Central Zone',
                'address' => '120 Center Blvd',
                'slot' => '12:00–14:00',
                'slot_label' => 'Today',
                'placed_at' => '06:22 AM',
                'urgent' => false,
                'value' => 72.10,
                'items' => 7,
                'payment' => 'apple',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'ready',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8770-DEF',
                'store' => 'westside',
                'driver' => 'DRV-1104',
                'customer' => 'Daniel Kim',
                'phone' => '+1 555-0121',
                'area' => 'West Zone',
                'address' => '33 Bay Street, West',
                'slot' => '08:00–10:00',
                'slot_label' => 'Today',
                'placed_at' => '05:58 AM',
                'urgent' => false,
                'value' => 110.00,
                'items' => 9,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'delivered',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8762-GHI',
                'store' => 'downtown',
                'driver' => 'DRV-8492',
                'customer' => 'Anna Bell',
                'phone' => '+1 555-0190',
                'area' => 'North Zone',
                'address' => '12 Cedar Way, North',
                'slot' => '08:00–10:00',
                'slot_label' => 'Yesterday',
                'placed_at' => '05:20 AM',
                'urgent' => false,
                'value' => 78.00,
                'items' => 5,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'delivered',
                'eta' => null,
            ],
            [
                'code' => 'ORD-8755-JKL',
                'store' => 'uptown',
                'driver' => 'DRV-5510',
                'customer' => 'Laura Kim',
                'phone' => '+1 555-0144',
                'area' => 'Central Zone',
                'address' => '18 Center Plaza',
                'slot' => '08:00–10:00',
                'slot_label' => 'Yesterday',
                'placed_at' => '04:48 AM',
                'urgent' => false,
                'value' => 88.00,
                'items' => 6,
                'payment' => 'cod',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'delivered',
                'eta' => null,
            ],

            // Live-map orders (currently out for delivery)
            [
                'code' => 'ORD-8924',
                'store' => 'downtown',
                'driver' => 'DRV-9001',
                'customer' => 'Olivia Bennett',
                'phone' => null,
                'area' => 'Manhattan Core',
                'address' => '123 Main St',
                'slot' => 'Now',
                'slot_label' => 'Today',
                'placed_at' => null,
                'urgent' => false,
                'value' => 56.20,
                'items' => 4,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'out',
                'eta' => '12 mins',
                'distance_km' => 2.4,
                'lat' => 40.7139,
                'lng' => -74.0035,
            ],
            [
                'code' => 'ORD-8925',
                'store' => 'uptown',
                'driver' => 'DRV-9002',
                'customer' => 'Noah Carter',
                'phone' => null,
                'area' => 'Manhattan Core',
                'address' => '789 Broadway St',
                'slot' => 'Now',
                'slot_label' => 'Today',
                'placed_at' => null,
                'urgent' => false,
                'value' => 41.00,
                'items' => 3,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'out',
                'eta' => '5 mins',
                'distance_km' => 1.1,
                'lat' => 40.7268,
                'lng' => -74.0121,
            ],
            [
                'code' => 'ORD-8930',
                'store' => 'westside',
                'driver' => 'DRV-9003',
                'customer' => 'Ava Mitchell',
                'phone' => null,
                'area' => 'Manhattan Core',
                'address' => '456 Elm St',
                'slot' => 'Now',
                'slot_label' => 'Today',
                'placed_at' => null,
                'urgent' => false,
                'value' => 88.75,
                'items' => 7,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'out',
                'eta' => '20 mins',
                'distance_km' => 3.7,
                'lat' => 40.7069,
                'lng' => -73.9931,
            ],
            [
                'code' => 'ORD-8932',
                'store' => 'harbor',
                'driver' => 'DRV-9006',
                'customer' => 'Liam Foster',
                'phone' => null,
                'area' => 'Manhattan Core',
                'address' => '101 Pine St',
                'slot' => 'Now',
                'slot_label' => 'Today',
                'placed_at' => null,
                'urgent' => false,
                'value' => 33.40,
                'items' => 2,
                'payment' => 'online',
                'prep' => 'ready',
                'prep_pct' => 100,
                'delivery' => 'out',
                'eta' => '3 mins',
                'distance_km' => 0.8,
                'lat' => 40.7121,
                'lng' => -74.0108,
            ],
        ];

        foreach ($orders as $o) {
            Order::updateOrCreate(
                ['code' => $o['code']],
                [
                    'store_id' => $storesByCode[$o['store']] ?? null,
                    'driver_id' => isset($o['driver']) ? ($driversByCode[$o['driver']] ?? null) : null,
                    'customer' => $o['customer'],
                    'phone' => $o['phone'] ?? null,
                    'area' => $o['area'] ?? null,
                    'address' => $o['address'] ?? null,
                    'slot' => $o['slot'] ?? null,
                    'slot_label' => $o['slot_label'] ?? null,
                    'placed_at' => $o['placed_at'] ?? null,
                    'urgent' => (bool) ($o['urgent'] ?? false),
                    'value' => (float) ($o['value'] ?? 0),
                    'items' => (int) ($o['items'] ?? 0),
                    'payment' => $o['payment'] ?? null,
                    'prep' => $o['prep'] ?? null,
                    'prep_pct' => (int) ($o['prep_pct'] ?? 0),
                    'delivery' => $o['delivery'] ?? null,
                    'eta' => $o['eta'] ?? null,
                    'distance_km' => $o['distance_km'] ?? null,
                    'lat' => $o['lat'] ?? null,
                    'lng' => $o['lng'] ?? null,
                ]
            );
        }
    }
}
