<?php

return [
    'metrics' => [
        'new' => 24,
        'waiting' => 27,
        'assigned' => 32,
        'accepted' => 14,
        'ready' => 21,
        'out' => 16,
        'delivered' => 48,
    ],
    'stores' => [
        ['id' => 'downtown', 'name' => 'Downtown Fresh Market', 'count' => 42],
        ['id' => 'uptown', 'name' => 'Uptown Express', 'count' => 31],
        ['id' => 'westside', 'name' => 'Westside Grocer', 'count' => 28],
        ['id' => 'harbor', 'name' => 'Harbor Market', 'count' => 19],
    ],
    'areas' => ['North Zone', 'South Zone', 'East Zone', 'West Zone', 'Central Zone'],
    'slots' => ['08:00–10:00', '10:00–12:00', '12:00–14:00', '14:00–16:00', '16:00–18:00', '18:00–20:00'],
    'orders' => [
        [
            'id' => 'ORD-8823-XYZ',
            'placed_at' => '08:14 AM',
            'customer' => 'Sarah Jenkins',
            'phone' => '+1 555-0142',
            'area' => 'North Zone',
            'address' => '214 Maple St, North District',
            'store' => 'Downtown Fresh Market',
            'store_id' => 'downtown',
            'slot' => '10:00–12:00',
            'slot_label' => 'Today',
            'urgent' => true,
            'value' => 84.50,
            'items' => 6,
            'payment' => 'online',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'waiting',
            'driver' => null,
            'view' => ['urgent', 'unassigned'],
        ],
        [
            'id' => 'ORD-8819-ABC',
            'placed_at' => '07:52 AM',
            'customer' => 'Michael Chen',
            'phone' => '+1 555-0198',
            'area' => 'Central Zone',
            'address' => '88 Market Ave, Central',
            'store' => 'Uptown Express',
            'store_id' => 'uptown',
            'slot' => '10:00–12:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 62.00,
            'items' => 4,
            'payment' => 'cod',
            'prep' => 'packing',
            'prep_pct' => 55,
            'delivery' => 'assigned',
            'driver' => ['name' => 'David Rodriguez', 'id' => 'DRV-4412', 'eta' => '22m', 'avatar' => '5.png'],
            'view' => [],
        ],
        [
            'id' => 'ORD-8815-QWE',
            'placed_at' => '07:41 AM',
            'customer' => 'Emily Watson',
            'phone' => '+1 555-0110',
            'area' => 'West Zone',
            'address' => '15 Harbor Rd, Westside',
            'store' => 'Westside Grocer',
            'store_id' => 'westside',
            'slot' => '12:00–14:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 145.50,
            'items' => 11,
            'payment' => 'apple',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'waiting',
            'request_pending' => true,
            'driver' => null,
            'view' => ['unassigned'],
        ],
        [
            'id' => 'ORD-8808-RST',
            'placed_at' => '07:18 AM',
            'customer' => 'James Parker',
            'phone' => '+1 555-0166',
            'area' => 'South Zone',
            'address' => '402 Oak Lane, South',
            'store' => 'Harbor Market',
            'store_id' => 'harbor',
            'slot' => '10:00–12:00',
            'slot_label' => 'Today',
            'urgent' => true,
            'value' => 39.90,
            'items' => 3,
            'payment' => 'online',
            'prep' => 'not_started',
            'prep_pct' => 0,
            'delivery' => 'new',
            'driver' => null,
            'view' => ['urgent', 'unassigned'],
        ],
        [
            'id' => 'ORD-8801-LMN',
            'placed_at' => '06:55 AM',
            'customer' => 'Priya Sharma',
            'phone' => '+1 555-0177',
            'area' => 'East Zone',
            'address' => '9 River Walk, East End',
            'store' => 'Downtown Fresh Market',
            'store_id' => 'downtown',
            'slot' => '08:00–10:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 98.25,
            'items' => 8,
            'payment' => 'online',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'out',
            'driver' => ['name' => 'Alex Chen', 'id' => 'DRV-2281', 'eta' => '14m', 'avatar' => '1.png'],
            'view' => ['in_transit'],
        ],
        [
            'id' => 'ORD-8794-TUV',
            'placed_at' => '06:40 AM',
            'customer' => 'Robert Davis',
            'phone' => '+1 555-0133',
            'area' => 'North Zone',
            'address' => '71 Pine Court, North',
            'store' => 'Uptown Express',
            'store_id' => 'uptown',
            'slot' => '14:00–16:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 54.00,
            'items' => 5,
            'payment' => 'cod',
            'prep' => 'packing',
            'prep_pct' => 40,
            'delivery' => 'accepted',
            'driver' => ['name' => 'Sarah Connor', 'id' => 'DRV-3390', 'eta' => '35m', 'avatar' => '6.png'],
            'view' => [],
        ],
        [
            'id' => 'ORD-8788-OPQ',
            'placed_at' => '06:22 AM',
            'customer' => 'Lisa Nguyen',
            'phone' => '+1 555-0188',
            'area' => 'Central Zone',
            'address' => '120 Center Blvd',
            'store' => 'Downtown Fresh Market',
            'store_id' => 'downtown',
            'slot' => '12:00–14:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 72.10,
            'items' => 7,
            'payment' => 'apple',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'ready',
            'driver' => null,
            'view' => ['unassigned'],
        ],
        [
            'id' => 'ORD-8770-DEF',
            'placed_at' => '05:58 AM',
            'customer' => 'Daniel Kim',
            'phone' => '+1 555-0121',
            'area' => 'West Zone',
            'address' => '33 Bay Street, West',
            'store' => 'Westside Grocer',
            'store_id' => 'westside',
            'slot' => '08:00–10:00',
            'slot_label' => 'Today',
            'urgent' => false,
            'value' => 110.00,
            'items' => 9,
            'payment' => 'online',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'delivered',
            'driver' => ['name' => 'Mike Johnson', 'id' => 'DRV-1104', 'eta' => null, 'avatar' => '7.png'],
            'view' => ['delivered'],
        ],
        [
            'id' => 'ORD-8762-GHI',
            'placed_at' => '05:20 AM',
            'customer' => 'Anna Bell',
            'phone' => '+1 555-0190',
            'area' => 'North Zone',
            'address' => '12 Cedar Way, North',
            'store' => 'Downtown Fresh Market',
            'store_id' => 'downtown',
            'slot' => '08:00–10:00',
            'slot_label' => 'Yesterday',
            'urgent' => false,
            'value' => 78.00,
            'items' => 5,
            'payment' => 'online',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'delivered',
            'driver' => ['name' => 'Michael Chen', 'id' => 'DRV-8492', 'eta' => null, 'avatar' => '5.png'],
            'view' => ['delivered'],
        ],
        [
            'id' => 'ORD-8755-JKL',
            'placed_at' => '04:48 AM',
            'customer' => 'Laura Kim',
            'phone' => '+1 555-0144',
            'area' => 'Central Zone',
            'address' => '18 Center Plaza',
            'store' => 'Uptown Express',
            'store_id' => 'uptown',
            'slot' => '08:00–10:00',
            'slot_label' => 'Yesterday',
            'urgent' => false,
            'value' => 88.00,
            'items' => 6,
            'payment' => 'cod',
            'prep' => 'ready',
            'prep_pct' => 100,
            'delivery' => 'delivered',
            'driver' => ['name' => 'Priya Nair', 'id' => 'DRV-5510', 'eta' => null, 'avatar' => '6.png'],
            'view' => ['delivered'],
        ],
    ],
    'nearby_drivers' => [
        [
            'id' => 'DRV-8492',
            'name' => 'Michael Chen',
            'vehicle' => 'VAN-492A',
            'vehicle_type' => 'van',
            'status' => 'available',
            'load' => 1,
            'distance' => '0.8 mi',
            'eta' => '3 mins',
            'recommended' => true,
            'note' => null,
            'avatar' => '5.png',
            'type' => 'store',
            'store_id' => 'downtown',
            'store_name' => 'Downtown Fresh Market',
        ],
        [
            'id' => 'DRV-2281',
            'name' => 'Alex Chen',
            'vehicle' => 'SCOOT-15',
            'vehicle_type' => 'scooter',
            'status' => 'available',
            'load' => 0,
            'distance' => '1.4 mi',
            'eta' => '5 mins',
            'recommended' => false,
            'note' => null,
            'avatar' => '2.png',
            'type' => 'store',
            'store_id' => 'downtown',
            'store_name' => 'Downtown Fresh Market',
        ],
        [
            'id' => 'DRV-5102',
            'name' => 'Priya Nair',
            'vehicle' => 'BIKE-510',
            'vehicle_type' => 'bike',
            'status' => 'available',
            'load' => 1,
            'distance' => '1.1 mi',
            'eta' => '4 mins',
            'recommended' => true,
            'note' => null,
            'avatar' => '6.png',
            'type' => 'store',
            'store_id' => 'uptown',
            'store_name' => 'Uptown Express',
        ],
        [
            'id' => 'DRV-3301',
            'name' => 'James Turner',
            'vehicle' => 'VAN-301B',
            'vehicle_type' => 'van',
            'status' => 'available',
            'load' => 0,
            'distance' => '0.6 mi',
            'eta' => '2 mins',
            'recommended' => true,
            'note' => null,
            'avatar' => '7.png',
            'type' => 'store',
            'store_id' => 'westside',
            'store_name' => 'Westside Grocer',
        ],
        [
            'id' => 'DRV-4401',
            'name' => 'Maria Lopez',
            'vehicle' => 'SCOOT-401',
            'vehicle_type' => 'scooter',
            'status' => 'available',
            'load' => 2,
            'distance' => '1.8 mi',
            'eta' => '6 mins',
            'recommended' => false,
            'note' => null,
            'avatar' => '4.png',
            'type' => 'store',
            'store_id' => 'harbor',
            'store_name' => 'Harbor Market',
        ],
    ],
];
